[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
glam = { version = "0.30.1", features = [] }
image = "0.25.6"
minifb = "0.28.0"
num = "0.4.3"
rand = "0.9.0"
rand_xoshiro = "0.7.0"
